#!/bin/sh
# Copyright (C) 2024 Checkmk GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.
# This check is always CRITICAL and prints the message passed in it's arguments back

case "$1" in
    -h | --help | "")
        echo "usage: $(basename "$0") MESSAGE [...]"
        echo "Always returns CRITICAL and prints the given message."
        exit 3
        ;;
esac

printf -- "%s\n" "$*"
exit 2
